#5 Mapping of elements of BPMN.xml file to docu elements
jenshb/camunda-bpmn-documentation-generator pull request #10
Opened 2021-10-15 13:46 UTC by jenshb

2021-11-12 14:14 UTC, ykstr reviewed
BpmnParser throws a NoSuchElementException if a process contains no documentation. Should we still document the id, name and version tag with some kind of placeholder text ("No documentation available" or something along those lines)?

2021-11-12 15:08 UTC, ahsNT requested changes

2021-11-12 15:08 UTC, ahsNT commented on build.gradle.kts
> +    implementation("org.camunda.bpm.model:camunda-bpmn-model:7.16.0")
We already have a dependencies section, this can be moved there

2021-11-19 16:33 UTC, jenshb commented on src/main/kotlin/models/BpmnObject.kt
> +data class BpmnObject(val id: String, val name: String, val version: String, val documentation: String)
Done

2021-12-10 08:30 UTC, merged